version: "3.8"

services:
  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    command: /bin/sh -c "ollama pull qwen2.5-coder:0.5b && /bin/bash"

  webchat:
    build: ./webchat
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    command: /bin/sh -c "until nc -z -v -w30 ollama 11434; do echo 'Waiting for Ollama to be ready...'; sleep 2; done && npm start"
    restart: unless-stopped

volumes:
  ollama_data:
